#!/usr/bin/python3
import sys
import time
import pexpect

def relax(p, timeout):
    try:
        while p.isalive():
            p.read_nonblocking(100, timeout=timeout)
    except pexpect.exceptions.TIMEOUT:
        pass


p = pexpect.spawnu("bash")
p.logfile = sys.stdout
p.expect_exact("$ ")

p.sendline("cd /home/aran/text-world/evennia")
p.expect_exact("$ ")

choice = None
if len(sys.argv) > 1:
    choice = sys.argv[1]
    assert choice in ("master", "fantasy")
    p.sendline("git checkout " + choice)
    p.readline()
    p.expect_exact("$ ")

p.sendline("git rev-parse --abbrev-ref HEAD")
p.readline()
branch = p.readline()[:-2]
assert branch in ("master", "fantasy")
if choice:
    assert branch == choice

p.expect_exact("$ ")

p.sendline("./start.sh 1")
p.expect_exact("Username: ")
p.sendline("root")
p.expect_exact("Email address: ")
p.sendline("root@root.com")
p.expect_exact("Password: ")
p.sendline("root")
p.expect_exact("Password (again): ")
p.sendline("root")
relax(p, 1)

p = pexpect.spawnu("rlwrap", ["telnet", "localhost", "4001"])
p.logfile = sys.stdout
relax(p, 1)
p.sendline("connect root root")
relax(p, 1)
if branch == "master":
    p.sendline("@batchcommand text_sims.build")
else:
    p.sendline("@batchcommand tutorial_world.build")
relax(p, 1)
p.logfile = None
p.sendline("@quell")
p.interact()
